### PR TITLE
upgrade GZoltar

### PR DESCRIPTION
**Pull request by jianguda**

### CODE REVIEW

**Comment by jianguda** [comment]
Hey @martinezmatias 
This PR is to replace #181 
Could you please release one new version of `Astor` after this PR gets merged?

**Comment by martinezmatias** [comment]
Hi @jianguda 
Thanks for the PR.

> Could you please release one new version of Astor after this PR gets merged?

Do you mean a release to Maven Central?

**Comment by jianguda** [comment]
> Do you mean a release to Maven Central?

Yes

**Comment by martinezmatias** [comment]
I don remember if we have already released to Maven Central. At least I havent done that yet. WDYT?

**Comment by jianguda** [comment]
> I don remember if we have already released to Maven Central. At least I havent done that yet. WDYT?

It seems that we should push latest `Astor` to [Thomas's repo](https://github.com/tdurieux/maven-repository/tree/master/releases/org/inria/sacha/automaticRepair/astor), instead of making one release to Maven Central.

Hey @tdurieux , could you please release latest `Astor` to your __`maven-repository`__ repo. Its commit ID should be `f97339f6cd0dbfa5276c8cc45be62e4ba802be73`.

**Comment by monperrus** [comment]
I'm releasing it to Thomas' repo.

**Comment by monperrus** [comment]
Done, released version 20190905

https://github.com/tdurieux/maven-repository/tree/master/releases/org/inria/sacha/automaticRepair/astor/20190905

**Comment by martinezmatias** [comment]
Even the new dependency of GZoltar 1.72 was added in the pom.xml, the code continues using Gzoltar 0.1.1 (dependency retrieved from Nopol)
I open a new issue for doing the migration: https://github.com/SpoonLabs/astor/issues/197

**Pull request merged**
