### PR TITLE
ref: log4j migration + spoon 8.3

### PR DESCRIPTION
**Pull request by monperrus**
Fixing https://ci.inria.fr/sos/job/astor/735/

### CODE REVIEW

**Comment by monperrus** [comment]
@martinezmatias I'm still on it, in order to have CI green again.

**Comment by martinezmatias** [comment]
Hi @monperrus 
Perfect, Thanks!

**Comment by monperrus** [comment]
@martinezmatias CI is green :)

**Comment by martinezmatias** [comment]
Great @martinezmatias ! amazing hard work!

**Pull request merged**
