### PR TITLE
Enable testing in Github Actions

### PR DESCRIPTION
**Pull request by andre15silva**
- Removes travis-ci config files
- Introduces test workflow for github actions

### CODE REVIEW

**Comment by andre15silva** [comment]
An admin needs to enable Actions here.

https://github.com/andre15silva/astor/actions/runs/1055668915 is green.

**Comment by martinezmatias** [comment]
Amazing @andre15silva 
Ready to merge?

**Comment by andre15silva** [comment]
> Ready to merge?

No, you need to activate Actions on this repo. I don't have the permission, so I could only run them on my fork.

**Comment by martinezmatias** [comment]
>  I don't have the permission, so I could only run them on my fork.

Permission granted, you should receive an invitation

**Comment by andre15silva** [comment]
Ok, I think it needs to be merged to run @martinezmatias, so I'd say go ahead.

**Comment by martinezmatias** [comment]
Hi @andre15silva 
Merged, sorry for the delay.

**Pull request merged**
