### PR TITLE
Add spoon 6.0.0 support

### PR DESCRIPTION
**Pull request by tdurieux**

### CODE REVIEW

**Comment by tdurieux** [comment]
I am pretty sure that the 2failing tests are due to flaky build. Could you restart the two failing builds?
Thanks

**Comment by martinezmatias** [comment]
Restarted

**Comment by tdurieux** [comment]
spoon 6 brokes something in testCardumentM70ExhausitveMaxLimited but no idea why

**Comment by martinezmatias** [comment]
I ll check what's happening

**Comment by tdurieux** [comment]
and the other is a timeout: exec > 50min

**Pull request merged**
