### PR TITLE
upgrade `gzoltar` to latest version

### PR DESCRIPTION
**Pull request by jianguda**

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @jaxxgu 
Do you need the upgrade for a particular reason? an existing bug? performance?
Cheers
Matias

**Comment by jaxxgu** [comment]
> Hi @jaxxgu
> Do you need the upgrade for a particular reason? an existing bug? performance?
> Cheers
> Matias

Hey Matias

Yes, I am trying to solve issues happened at Repairnator. I also want someone to release Astor to maven, who should I contact (last time I contacted Martin)?

**Comment by martinezmatias** [comment]
Hi @jaxxgu 

> I also want someone to release Astor to maven

That would be perfect.

> Yes, I am trying to solve issues happened at Repairnator.

Is that related to the fault localisation GZoltar?
I should repair the failing test case in Astor, but, beyond that, as far I remember, I had some problems when I tried the Gzoltar version 1.x some time ago.

**Comment by jaxxgu** [comment]
Hey @martinezmatias 
I think it relates to `gzoltar` and you could check [this](https://github.com/Spirals-Team/repairnator/pull/932#issuecomment-526540293).

**Comment by jianguda** [comment]
waiting one stable CI #182 and switching to openJDK

**Comment by martinezmatias** [comment]
Hi Jian

Okey, I am working in the stabilisation on branch https://github.com/SpoonLabs/astor/tree/failingtests

**Pull request closed without merging**
