### PR TITLE
Add anti-pattern in EvolutionarySearchEngine

### PR DESCRIPTION
**Pull request by WuYff**
- Related issue
  - #245 
- Implemented anti-patterns
  - Anti-delete control statement 
  - Anti-append early exit  
  - Anti-append trivial condition

### CODE REVIEW

**Comment by martinezmatias** [comment]
Dear @WuYff 

Thanks a lot for this PR, that is amazing!
It would be great if we can have a test case for each anti-pattern you have encoded.
What do you think?
Thanks!
Matias

(BTW, our CI Travis was failing before your PR, I'll fix it asap)

**Comment by WuYff** [comment]
Dear @martinezmatias ,
Thanks for your quick feedback! 
It's necessary to have test cases. I am not so clear about how to construct the test inputs now but I will start to work on that :)

**Comment by martinezmatias** [comment]
Thanks @WuYff 
I inspected the code you have pushed and it's perfect! Thanks a lot.

**Comment by WuYff** [comment]
Dear @martinezmatias 
Thanks for your review! I have added the test cases

**Pull request merged**
