### PR TITLE
Changed order of execution in AbstractMain.java

### PR DESCRIPTION
**Pull request by javierron**
Solves https://github.com/SpoonLabs/astor/issues/238

Signed-off-by: Javier Ron <javierron90@gmail.com>

### CODE REVIEW

**Comment by javierron** [comment]
Jobs # 3 and # 5 are failing here, but passing on my repo's CI (https://travis-ci.com/github/javierron/astor/builds/174187951).

Could we re-run those jobs? I just want to be sure if it was me that broke the tests or they are somehow flaky.

**Comment by martinezmatias** [comment]
Hi @javierron 
Thanks for the PR!
Since some weeks ago, I cannot reset (and control) the Astor's task on Travis. No idea what happened.
In you Ci, there are two failing test (jGenProgTest) and (PatchDiffTest). Could you restart them? (there are lot of flaky test on Travis)
Regards
Matias

**Comment by javierron** [comment]
I have reset the jobs now, although PatchDiffTest seems to be consistently failing since a couple of commits ago.

Also, JGenProgTest seems to be not failing but timing out, perhaps it can be split in two (or more) jobs?

**Comment by monperrus** [comment]
> Since some weeks ago, I cannot reset (and control) the Astor's task on Travis.

Tip: Log out, remove cache, log-in again.

**Comment by monperrus** [comment]
@martinezmatias CI seems unrelated, merge?

**Comment by martinezmatias** [comment]
Hi @monperrus 

> Tip: Log out, remove cache, log-in again.

I will try, thanks!

> CI seems unrelated, merge?

Yes. Merged.

Thanks @javierron !

**Pull request merged**
