### PR TITLE
Flacoco support

### LINKED ISSUE #314: integrate flacoco in Astor
for @andre15silva

### PR DESCRIPTION
**Pull request by andre15silva**
Closes #314.

### CODE REVIEW

**Comment by andre15silva** [comment]
@martinezmatias 

You can find 3 examples under `FaultLocalizationExtensionTest`.

The first two are passing, and are example small projects.

The last one is `math85`, and if you run it you'll get the error we talked about in #314 .

```
testFlacocoExtensionMath85(fr.inria.astor.test.repair.evaluation.extensionpoints.FaultLocalizationExtensionTest)  Time elapsed: 207.793 sec  <<< ERROR!
java.lang.RuntimeException: Forked process did not finished correctly
	at eu.stamp_project.testrunner.EntryPoint.runGivenCommandLine(EntryPoint.java:599)
	at eu.stamp_project.testrunner.EntryPoint.runCoveredTestResultPerTestMethods(EntryPoint.java:496)
	at eu.stamp_project.testrunner.EntryPoint.runCoveredTestResultPerTestMethods(EntryPoint.java:446)
	at fr.spoonlabs.flacoco.core.coverage.framework.JUnit4Strategy.execute(JUnit4Strategy.java:23)
	at fr.spoonlabs.flacoco.core.coverage.CoverageRunner.getCoverageMatrix(CoverageRunner.java:35)
	at fr.spoonlabs.flacoco.localization.spectrum.SpectrumRunner.computeCoverageMatrix(SpectrumRunner.java:37)
	at fr.spoonlabs.flacoco.localization.spectrum.SpectrumRunner.run(SpectrumRunner.java:22)
	at fr.spoonlabs.flacoco.api.Flacoco.runDefault(Flacoco.java:32)
	at fr.inria.astor.core.faultlocalization.flacoco.FlacocoFaultLocalization.searchSuspicious(FlacocoFaultLocalization.java:30)
	at fr.inria.astor.core.solutionsearch.AstorCoreEngine.calculateSuspicious(AstorCoreEngine.java:903)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:119)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:173)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:233)
	at fr.inria.astor.test.repair.evaluation.extensionpoints.FaultLocalizationExtensionTest.runMath85(FaultLocalizationExtensionTest.java:204)
	at fr.inria.astor.test.repair.evaluation.extensionpoints.FaultLocalizationExtensionTest.testFlacocoExtensionMath85(FaultLocalizationExtensionTest.java:53)
```

**Comment by andre15silva** [comment]
Any way we can get CI enabled @martinezmatias ?

**Comment by martinezmatias** [comment]
Hi @andre15silva 

> Any way we can get CI enabled @martinezmatias ?

Ideally we should move to Actions. Travis.org is death so instead of moving to travis.com we should go to Actions.

**Comment by andre15silva** [comment]
> Ideally we should move to Actions. Travis.org is death so instead of moving to travis.com we should go to Actions.

Ok, I'll take care of that then. I was running the travis config on my personal account, but ran out of tokens quickly. Actions is for sure a better option.

**Comment by martinezmatias** [comment]
Perfect @andre15silva , thanks

**Comment by martinezmatias** [comment]
During the migration, it would be convenient to remove some low quality test (lot of smoke test) which require large execution times.

**Comment by andre15silva** [comment]
Currently blocked by https://github.com/SpoonLabs/flacoco/pull/79

**Comment by martinezmatias** [comment]
Nice work @andre15silva . Thanks! 

> so it would be nice if you could give me some feedback on those (if they are correct, if we can ignore them, if we should fix them, etc) as I don't have the entire context of how Astor and the tools work.

Ok, I merge now and then we update the tests doing other PR.

**Pull request merged**
