### PR TITLE
Integration of Flacoco

### PR DESCRIPTION
**Pull request by martinezmatias**

### CODE REVIEW

**Comment by martinezmatias** [comment]
@monperrus @javierron 

Initial code for the integration: we have the first test case running and passing on Math_85

**Comment by monperrus** [comment]
Nice milestone! Without any performance downside?

**Comment by monperrus** [comment]
> Now, the challenge is to reduce the execution time: Flacoco takes 211 seconds while Gzoltar 17 secs :/

Yes, one easy solution is to group the passing and failing together.

**Comment by monperrus** [comment]
Superseded by https://github.com/SpoonLabs/astor/pull/323

**Pull request closed without merging**
